server.port: ${port:8080}
kafka-global-consumer.bootstrap-servers: "192.168.99.100:9092"
  # The value comes from the Embedded Kafka: ${spring.embedded.kafka.brokers}


bootstrap:
  servers: "192.168.99.100:9092"

app:
  topic:
    example: topic.01
    record: topic.02

spring:
  h2.console.enabled: true
  #spring.datasource.url=jdbc:h2:mem:accountDB
  datasource.url: "jdbc:h2:~/pads-record-generator;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE"
  datasource:
    password: ''
    driverClassName: "org.h2.Driver"
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE